# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'batchform.ui'
#
# Created: Sun Jul 07 15:53:38 2013
#      by: PyQt4 UI code generator 4.9.6
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_BatchForm(object):
    def setupUi(self, BatchForm):
        BatchForm.setObjectName(_fromUtf8("BatchForm"))
        BatchForm.resize(763, 591)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(_fromUtf8(":/icons/batch")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        BatchForm.setWindowIcon(icon)
        self.detailView = QtGui.QTableView(BatchForm)
        self.detailView.setGeometry(QtCore.QRect(20, 184, 728, 214))
        self.detailView.setObjectName(_fromUtf8("detailView"))
        self.memoTextedit = QtGui.QTextEdit(BatchForm)
        self.memoTextedit.setGeometry(QtCore.QRect(528, 464, 215, 106))
        self.memoTextedit.setObjectName(_fromUtf8("memoTextedit"))
        self.label_8 = QtGui.QLabel(BatchForm)
        self.label_8.setGeometry(QtCore.QRect(530, 444, 46, 25))
        self.label_8.setMinimumSize(QtCore.QSize(0, 25))
        self.label_8.setMaximumSize(QtCore.QSize(16777215, 25))
        self.label_8.setObjectName(_fromUtf8("label_8"))
        self.label_9 = QtGui.QLabel(BatchForm)
        self.label_9.setGeometry(QtCore.QRect(250, 408, 203, 20))
        self.label_9.setMinimumSize(QtCore.QSize(0, 20))
        self.label_9.setMaximumSize(QtCore.QSize(16777215, 20))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(120, 120, 120))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(120, 120, 120))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Window, brush)
        self.label_9.setPalette(palette)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_9.setFont(font)
        self.label_9.setAutoFillBackground(True)
        self.label_9.setFrameShape(QtGui.QFrame.NoFrame)
        self.label_9.setObjectName(_fromUtf8("label_9"))
        self.multFactorLineedit = QtGui.QLineEdit(BatchForm)
        self.multFactorLineedit.setGeometry(QtCore.QRect(358, 429, 96, 20))
        self.multFactorLineedit.setMinimumSize(QtCore.QSize(96, 20))
        self.multFactorLineedit.setMaximumSize(QtCore.QSize(96, 20))
        self.multFactorLineedit.setFrame(True)
        self.multFactorLineedit.setObjectName(_fromUtf8("multFactorLineedit"))
        self.label_10 = QtGui.QLabel(BatchForm)
        self.label_10.setGeometry(QtCore.QRect(250, 429, 109, 20))
        self.label_10.setMinimumSize(QtCore.QSize(0, 20))
        self.label_10.setMaximumSize(QtCore.QSize(16777215, 20))
        self.label_10.setFrameShape(QtGui.QFrame.Box)
        self.label_10.setLineWidth(1)
        self.label_10.setObjectName(_fromUtf8("label_10"))
        self.frame = QtGui.QFrame(BatchForm)
        self.frame.setGeometry(QtCore.QRect(20, 90, 730, 86))
        self.frame.setFrameShape(QtGui.QFrame.Box)
        self.frame.setFrameShadow(QtGui.QFrame.Sunken)
        self.frame.setObjectName(_fromUtf8("frame"))
        self.mult_Label = QtGui.QLabel(self.frame)
        self.mult_Label.setGeometry(QtCore.QRect(228, 7, 41, 25))
        self.mult_Label.setMinimumSize(QtCore.QSize(0, 25))
        self.mult_Label.setMaximumSize(QtCore.QSize(16777215, 25))
        self.mult_Label.setTextFormat(QtCore.Qt.PlainText)
        self.mult_Label.setWordWrap(True)
        self.mult_Label.setObjectName(_fromUtf8("mult_Label"))
        self.desc_Label = QtGui.QLabel(self.frame)
        self.desc_Label.setGeometry(QtCore.QRect(13, 47, 61, 25))
        self.desc_Label.setMinimumSize(QtCore.QSize(0, 25))
        self.desc_Label.setMaximumSize(QtCore.QSize(16777215, 25))
        self.desc_Label.setObjectName(_fromUtf8("desc_Label"))
        self.multLineedit = QtGui.QLineEdit(self.frame)
        self.multLineedit.setGeometry(QtCore.QRect(275, 7, 96, 25))
        self.multLineedit.setMinimumSize(QtCore.QSize(96, 25))
        self.multLineedit.setMaximumSize(QtCore.QSize(96, 25))
        self.multLineedit.setObjectName(_fromUtf8("multLineedit"))
        self.weight_Label = QtGui.QLabel(self.frame)
        self.weight_Label.setGeometry(QtCore.QRect(550, 41, 34, 25))
        self.weight_Label.setMinimumSize(QtCore.QSize(0, 25))
        self.weight_Label.setMaximumSize(QtCore.QSize(16777215, 25))
        self.weight_Label.setObjectName(_fromUtf8("weight_Label"))
        self.baseno_Label = QtGui.QLabel(self.frame)
        self.baseno_Label.setGeometry(QtCore.QRect(15, 7, 42, 25))
        self.baseno_Label.setMinimumSize(QtCore.QSize(0, 25))
        self.baseno_Label.setMaximumSize(QtCore.QSize(16777215, 25))
        self.baseno_Label.setObjectName(_fromUtf8("baseno_Label"))
        self.baseCombo = QtGui.QComboBox(self.frame)
        self.baseCombo.setGeometry(QtCore.QRect(83, 7, 96, 25))
        self.baseCombo.setMinimumSize(QtCore.QSize(96, 25))
        self.baseCombo.setMaximumSize(QtCore.QSize(96, 25))
        self.baseCombo.setObjectName(_fromUtf8("baseCombo"))
        self.volume_Label = QtGui.QLabel(self.frame)
        self.volume_Label.setGeometry(QtCore.QRect(550, 7, 59, 25))
        self.volume_Label.setMinimumSize(QtCore.QSize(0, 25))
        self.volume_Label.setMaximumSize(QtCore.QSize(16777215, 25))
        self.volume_Label.setObjectName(_fromUtf8("volume_Label"))
        self.volumeLineedit = QtGui.QLineEdit(self.frame)
        self.volumeLineedit.setGeometry(QtCore.QRect(615, 7, 96, 25))
        self.volumeLineedit.setMinimumSize(QtCore.QSize(96, 25))
        self.volumeLineedit.setMaximumSize(QtCore.QSize(96, 25))
        self.volumeLineedit.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.volumeLineedit.setObjectName(_fromUtf8("volumeLineedit"))
        self.date_Label = QtGui.QLabel(self.frame)
        self.date_Label.setGeometry(QtCore.QRect(390, 41, 23, 25))
        self.date_Label.setMinimumSize(QtCore.QSize(0, 25))
        self.date_Label.setMaximumSize(QtCore.QSize(16777215, 25))
        self.date_Label.setObjectName(_fromUtf8("date_Label"))
        self.descLineedit = QtGui.QLineEdit(self.frame)
        self.descLineedit.setGeometry(QtCore.QRect(83, 47, 288, 25))
        self.descLineedit.setMinimumSize(QtCore.QSize(288, 25))
        self.descLineedit.setMaximumSize(QtCore.QSize(288, 25))
        self.descLineedit.setObjectName(_fromUtf8("descLineedit"))
        self.v_weight_Label = QtGui.QLabel(self.frame)
        self.v_weight_Label.setGeometry(QtCore.QRect(615, 41, 96, 25))
        self.v_weight_Label.setMinimumSize(QtCore.QSize(96, 25))
        self.v_weight_Label.setMaximumSize(QtCore.QSize(96, 25))
        self.v_weight_Label.setFrameShape(QtGui.QFrame.Box)
        self.v_weight_Label.setText(_fromUtf8(""))
        self.v_weight_Label.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.v_weight_Label.setObjectName(_fromUtf8("v_weight_Label"))
        self.baseID_Label = QtGui.QLabel(self.frame)
        self.baseID_Label.setGeometry(QtCore.QRect(390, 7, 48, 25))
        self.baseID_Label.setMinimumSize(QtCore.QSize(0, 25))
        self.baseID_Label.setMaximumSize(QtCore.QSize(16777215, 25))
        self.baseID_Label.setObjectName(_fromUtf8("baseID_Label"))
        self.dateEdit = QtGui.QDateEdit(self.frame)
        self.dateEdit.setGeometry(QtCore.QRect(438, 41, 96, 25))
        self.dateEdit.setMinimumSize(QtCore.QSize(96, 25))
        self.dateEdit.setMaximumSize(QtCore.QSize(96, 25))
        self.dateEdit.setCalendarPopup(True)
        self.dateEdit.setObjectName(_fromUtf8("dateEdit"))
        self.v_baseID_Label = QtGui.QLabel(self.frame)
        self.v_baseID_Label.setGeometry(QtCore.QRect(438, 7, 96, 25))
        self.v_baseID_Label.setMinimumSize(QtCore.QSize(96, 25))
        self.v_baseID_Label.setMaximumSize(QtCore.QSize(96, 25))
        self.v_baseID_Label.setFrameShape(QtGui.QFrame.Box)
        self.v_baseID_Label.setText(_fromUtf8(""))
        self.v_baseID_Label.setObjectName(_fromUtf8("v_baseID_Label"))
        self.v_mult114lt_Label = QtGui.QLabel(BatchForm)
        self.v_mult114lt_Label.setGeometry(QtCore.QRect(358, 549, 94, 20))
        self.v_mult114lt_Label.setMinimumSize(QtCore.QSize(0, 20))
        self.v_mult114lt_Label.setMaximumSize(QtCore.QSize(16777215, 20))
        self.v_mult114lt_Label.setFrameShape(QtGui.QFrame.Box)
        self.v_mult114lt_Label.setText(_fromUtf8(""))
        self.v_mult114lt_Label.setObjectName(_fromUtf8("v_mult114lt_Label"))
        self.v_mult4lt_Label = QtGui.QLabel(BatchForm)
        self.v_mult4lt_Label.setGeometry(QtCore.QRect(358, 529, 94, 20))
        self.v_mult4lt_Label.setMinimumSize(QtCore.QSize(0, 20))
        self.v_mult4lt_Label.setMaximumSize(QtCore.QSize(16777215, 20))
        self.v_mult4lt_Label.setFrameShape(QtGui.QFrame.Box)
        self.v_mult4lt_Label.setText(_fromUtf8(""))
        self.v_mult4lt_Label.setObjectName(_fromUtf8("v_mult4lt_Label"))
        self.v_mult15lt_Label = QtGui.QLabel(BatchForm)
        self.v_mult15lt_Label.setGeometry(QtCore.QRect(358, 489, 94, 20))
        self.v_mult15lt_Label.setMinimumSize(QtCore.QSize(0, 20))
        self.v_mult15lt_Label.setMaximumSize(QtCore.QSize(16777215, 20))
        self.v_mult15lt_Label.setFrameShape(QtGui.QFrame.Box)
        self.v_mult15lt_Label.setText(_fromUtf8(""))
        self.v_mult15lt_Label.setObjectName(_fromUtf8("v_mult15lt_Label"))
        self.v_multFlu_Label = QtGui.QLabel(BatchForm)
        self.v_multFlu_Label.setGeometry(QtCore.QRect(358, 449, 94, 20))
        self.v_multFlu_Label.setMinimumSize(QtCore.QSize(0, 20))
        self.v_multFlu_Label.setMaximumSize(QtCore.QSize(16777215, 20))
        self.v_multFlu_Label.setFrameShape(QtGui.QFrame.Box)
        self.v_multFlu_Label.setText(_fromUtf8(""))
        self.v_multFlu_Label.setObjectName(_fromUtf8("v_multFlu_Label"))
        self.v_mult2lt_Label = QtGui.QLabel(BatchForm)
        self.v_mult2lt_Label.setGeometry(QtCore.QRect(358, 509, 94, 20))
        self.v_mult2lt_Label.setMinimumSize(QtCore.QSize(0, 20))
        self.v_mult2lt_Label.setMaximumSize(QtCore.QSize(16777215, 20))
        self.v_mult2lt_Label.setFrameShape(QtGui.QFrame.Box)
        self.v_mult2lt_Label.setText(_fromUtf8(""))
        self.v_mult2lt_Label.setObjectName(_fromUtf8("v_mult2lt_Label"))
        self.v_mult1lt_Label = QtGui.QLabel(BatchForm)
        self.v_mult1lt_Label.setGeometry(QtCore.QRect(358, 469, 94, 20))
        self.v_mult1lt_Label.setMinimumSize(QtCore.QSize(0, 20))
        self.v_mult1lt_Label.setMaximumSize(QtCore.QSize(16777215, 20))
        self.v_mult1lt_Label.setFrameShape(QtGui.QFrame.Box)
        self.v_mult1lt_Label.setText(_fromUtf8(""))
        self.v_mult1lt_Label.setObjectName(_fromUtf8("v_mult1lt_Label"))
        self.label_26 = QtGui.QLabel(BatchForm)
        self.label_26.setGeometry(QtCore.QRect(250, 549, 109, 20))
        self.label_26.setMinimumSize(QtCore.QSize(0, 20))
        self.label_26.setMaximumSize(QtCore.QSize(16777215, 20))
        self.label_26.setFrameShape(QtGui.QFrame.Box)
        self.label_26.setLineWidth(1)
        self.label_26.setObjectName(_fromUtf8("label_26"))
        self.label_27 = QtGui.QLabel(BatchForm)
        self.label_27.setGeometry(QtCore.QRect(250, 469, 109, 20))
        self.label_27.setMinimumSize(QtCore.QSize(0, 20))
        self.label_27.setMaximumSize(QtCore.QSize(16777215, 20))
        self.label_27.setFrameShape(QtGui.QFrame.Box)
        self.label_27.setLineWidth(1)
        self.label_27.setObjectName(_fromUtf8("label_27"))
        self.label_28 = QtGui.QLabel(BatchForm)
        self.label_28.setGeometry(QtCore.QRect(250, 529, 109, 20))
        self.label_28.setMinimumSize(QtCore.QSize(0, 20))
        self.label_28.setMaximumSize(QtCore.QSize(16777215, 20))
        self.label_28.setFrameShape(QtGui.QFrame.Box)
        self.label_28.setLineWidth(1)
        self.label_28.setObjectName(_fromUtf8("label_28"))
        self.label_29 = QtGui.QLabel(BatchForm)
        self.label_29.setGeometry(QtCore.QRect(250, 509, 109, 20))
        self.label_29.setMinimumSize(QtCore.QSize(0, 20))
        self.label_29.setMaximumSize(QtCore.QSize(16777215, 20))
        self.label_29.setFrameShape(QtGui.QFrame.Box)
        self.label_29.setLineWidth(1)
        self.label_29.setObjectName(_fromUtf8("label_29"))
        self.label_30 = QtGui.QLabel(BatchForm)
        self.label_30.setGeometry(QtCore.QRect(250, 489, 109, 20))
        self.label_30.setMinimumSize(QtCore.QSize(0, 20))
        self.label_30.setMaximumSize(QtCore.QSize(16777215, 20))
        self.label_30.setFrameShape(QtGui.QFrame.Box)
        self.label_30.setLineWidth(1)
        self.label_30.setObjectName(_fromUtf8("label_30"))
        self.label_31 = QtGui.QLabel(BatchForm)
        self.label_31.setGeometry(QtCore.QRect(250, 449, 109, 20))
        self.label_31.setMinimumSize(QtCore.QSize(0, 20))
        self.label_31.setMaximumSize(QtCore.QSize(16777215, 20))
        self.label_31.setFrameShape(QtGui.QFrame.Box)
        self.label_31.setLineWidth(1)
        self.label_31.setObjectName(_fromUtf8("label_31"))
        self.frame_2 = QtGui.QFrame(BatchForm)
        self.frame_2.setGeometry(QtCore.QRect(0, 41, 769, 37))
        self.frame_2.setAutoFillBackground(False)
        self.frame_2.setStyleSheet(_fromUtf8("border: none;\n"
"background: qlineargradient(x1: 0, y1: 0, x2: 0, y2: 1,\n"
"stop: 0 #BBBBBB, \n"
"stop: 0.4 #EEEEEE,\n"
"stop: 0.9 #CCCCCC,\n"
" stop: 1 #666666);"))
        self.frame_2.setFrameShape(QtGui.QFrame.Box)
        self.frame_2.setFrameShadow(QtGui.QFrame.Raised)
        self.frame_2.setObjectName(_fromUtf8("frame_2"))
        self.saveButton = QtGui.QPushButton(self.frame_2)
        self.saveButton.setGeometry(QtCore.QRect(111, 5, 90, 27))
        self.saveButton.setMinimumSize(QtCore.QSize(90, 0))
        self.saveButton.setMaximumSize(QtCore.QSize(90, 16777215))
        self.saveButton.setStyleSheet(_fromUtf8("QPushButton {\n"
"background-color: rgb(250, 250, 250);\n"
"color: #333;\n"
"border: 2px solid #555;\n"
"padding: 5px;}\n"
"QPushButton:hover {\n"
"background: qradialgradient(cx: 0.3, cy: -0.4,\n"
"fx: 0.3, fy: -0.4,\n"
"radius: 1.35, stop: 0 #fff, stop: 1 #ccc);}\n"
"QPushButton:pressed {\n"
"background: qradialgradient(cx: 0.4, cy: -0.1,\n"
"fx: 0.4, fy: -0.1,\n"
"radius: 1.35, stop: 0 #fff, stop: 1 #eee);}"))
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(_fromUtf8(":/icons/save")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.saveButton.setIcon(icon1)
        self.saveButton.setIconSize(QtCore.QSize(20, 20))
        self.saveButton.setFlat(False)
        self.saveButton.setObjectName(_fromUtf8("saveButton"))
        self.newButton = QtGui.QPushButton(self.frame_2)
        self.newButton.setGeometry(QtCore.QRect(15, 5, 90, 27))
        self.newButton.setMinimumSize(QtCore.QSize(90, 0))
        self.newButton.setMaximumSize(QtCore.QSize(90, 16777215))
        self.newButton.setStyleSheet(_fromUtf8("QPushButton {\n"
"background-color: rgb(250, 250, 250);\n"
"color: #333;\n"
"border: 2px solid #555;\n"
"padding: 5px;}\n"
"QPushButton:hover {\n"
"background: qradialgradient(cx: 0.3, cy: -0.4,\n"
"fx: 0.3, fy: -0.4,\n"
"radius: 1.35, stop: 0 #fff, stop: 1 #ccc);}\n"
"QPushButton:pressed {\n"
"background: qradialgradient(cx: 0.4, cy: -0.1,\n"
"fx: 0.4, fy: -0.1,\n"
"radius: 1.35, stop: 0 #fff, stop: 1 #eee);}"))
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(_fromUtf8(":/icons/new")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.newButton.setIcon(icon2)
        self.newButton.setIconSize(QtCore.QSize(20, 20))
        self.newButton.setFlat(False)
        self.newButton.setObjectName(_fromUtf8("newButton"))
        self.printButton = QtGui.QPushButton(self.frame_2)
        self.printButton.setGeometry(QtCore.QRect(303, 5, 90, 27))
        self.printButton.setMinimumSize(QtCore.QSize(90, 0))
        self.printButton.setMaximumSize(QtCore.QSize(90, 16777215))
        self.printButton.setStyleSheet(_fromUtf8("QPushButton {\n"
"background-color: rgb(250, 250, 250);\n"
"color: #333;\n"
"border: 2px solid #555;\n"
"padding: 5px;}\n"
"QPushButton:hover {\n"
"background: qradialgradient(cx: 0.3, cy: -0.4,\n"
"fx: 0.3, fy: -0.4,\n"
"radius: 1.35, stop: 0 #fff, stop: 1 #ccc);}\n"
"QPushButton:pressed {\n"
"background: qradialgradient(cx: 0.4, cy: -0.1,\n"
"fx: 0.4, fy: -0.1,\n"
"radius: 1.35, stop: 0 #fff, stop: 1 #eee);}"))
        self.printButton.setIconSize(QtCore.QSize(20, 20))
        self.printButton.setFlat(False)
        self.printButton.setObjectName(_fromUtf8("printButton"))
        self.deleteButton = QtGui.QPushButton(self.frame_2)
        self.deleteButton.setGeometry(QtCore.QRect(207, 5, 90, 27))
        self.deleteButton.setMinimumSize(QtCore.QSize(90, 0))
        self.deleteButton.setMaximumSize(QtCore.QSize(90, 16777215))
        self.deleteButton.setStyleSheet(_fromUtf8("QPushButton {\n"
"background-color: rgb(250, 250, 250);\n"
"color: #333;\n"
"border: 2px solid #555;\n"
"padding: 5px;}\n"
"QPushButton:hover {\n"
"background: qradialgradient(cx: 0.3, cy: -0.4,\n"
"fx: 0.3, fy: -0.4,\n"
"radius: 1.35, stop: 0 #fff, stop: 1 #ccc);}\n"
"QPushButton:pressed {\n"
"background: qradialgradient(cx: 0.4, cy: -0.1,\n"
"fx: 0.4, fy: -0.1,\n"
"radius: 1.35, stop: 0 #fff, stop: 1 #eee);}"))
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap(_fromUtf8(":/icons/delete")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.deleteButton.setIcon(icon3)
        self.deleteButton.setIconSize(QtCore.QSize(20, 20))
        self.deleteButton.setFlat(False)
        self.deleteButton.setObjectName(_fromUtf8("deleteButton"))
        self.closeButton = QtGui.QPushButton(self.frame_2)
        self.closeButton.setGeometry(QtCore.QRect(399, 5, 90, 27))
        self.closeButton.setMinimumSize(QtCore.QSize(90, 0))
        self.closeButton.setMaximumSize(QtCore.QSize(90, 16777215))
        self.closeButton.setStyleSheet(_fromUtf8("QPushButton {\n"
"background-color: rgb(250, 250, 250);\n"
"color: #333;\n"
"border: 2px solid #555;\n"
"padding: 5px;}\n"
"QPushButton:hover {\n"
"background: qradialgradient(cx: 0.3, cy: -0.4,\n"
"fx: 0.3, fy: -0.4,\n"
"radius: 1.35, stop: 0 #fff, stop: 1 #ccc);}\n"
"QPushButton:pressed {\n"
"background: qradialgradient(cx: 0.4, cy: -0.1,\n"
"fx: 0.4, fy: -0.1,\n"
"radius: 1.35, stop: 0 #fff, stop: 1 #eee);}"))
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap(_fromUtf8(":/icons/exit")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.closeButton.setIcon(icon4)
        self.closeButton.setIconSize(QtCore.QSize(20, 20))
        self.closeButton.setFlat(False)
        self.closeButton.setObjectName(_fromUtf8("closeButton"))
        self.groupBox = QtGui.QGroupBox(self.frame_2)
        self.groupBox.setGeometry(QtCore.QRect(546, 6, 188, 24))
        self.groupBox.setStyleSheet(_fromUtf8("background-color: rgb(212, 212, 212);"))
        self.groupBox.setTitle(_fromUtf8(""))
        self.groupBox.setObjectName(_fromUtf8("groupBox"))
        self.baseRadio = QtGui.QRadioButton(self.groupBox)
        self.baseRadio.setGeometry(QtCore.QRect(20, 5, 55, 17))
        self.baseRadio.setObjectName(_fromUtf8("baseRadio"))
        self.batchRadio = QtGui.QRadioButton(self.groupBox)
        self.batchRadio.setGeometry(QtCore.QRect(90, 4, 55, 17))
        self.batchRadio.setObjectName(_fromUtf8("batchRadio"))
        self.header_label = QtGui.QLabel(BatchForm)
        self.header_label.setGeometry(QtCore.QRect(85, -1, 259, 32))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Calibri"))
        font.setPointSize(20)
        font.setBold(True)
        font.setItalic(True)
        font.setUnderline(True)
        font.setWeight(75)
        self.header_label.setFont(font)
        self.header_label.setObjectName(_fromUtf8("header_label"))
        self.layoutWidget = QtGui.QWidget(BatchForm)
        self.layoutWidget.setGeometry(QtCore.QRect(620, 408, 126, 27))
        self.layoutWidget.setObjectName(_fromUtf8("layoutWidget"))
        self.horizontalLayout_2 = QtGui.QHBoxLayout(self.layoutWidget)
        self.horizontalLayout_2.setMargin(0)
        self.horizontalLayout_2.setObjectName(_fromUtf8("horizontalLayout_2"))
        self.label_12 = QtGui.QLabel(self.layoutWidget)
        self.label_12.setMinimumSize(QtCore.QSize(0, 25))
        self.label_12.setMaximumSize(QtCore.QSize(16777215, 25))
        self.label_12.setObjectName(_fromUtf8("label_12"))
        self.horizontalLayout_2.addWidget(self.label_12)
        self.v_cost_Label = QtGui.QLabel(self.layoutWidget)
        self.v_cost_Label.setMinimumSize(QtCore.QSize(96, 25))
        self.v_cost_Label.setMaximumSize(QtCore.QSize(96, 25))
        self.v_cost_Label.setFrameShape(QtGui.QFrame.Box)
        self.v_cost_Label.setText(_fromUtf8(""))
        self.v_cost_Label.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.v_cost_Label.setObjectName(_fromUtf8("v_cost_Label"))
        self.horizontalLayout_2.addWidget(self.v_cost_Label)
        self.layoutWidget1 = QtGui.QWidget(BatchForm)
        self.layoutWidget1.setGeometry(QtCore.QRect(20, 400, 219, 169))
        self.layoutWidget1.setObjectName(_fromUtf8("layoutWidget1"))
        self.verticalLayout_2 = QtGui.QVBoxLayout(self.layoutWidget1)
        self.verticalLayout_2.setMargin(0)
        self.verticalLayout_2.setObjectName(_fromUtf8("verticalLayout_2"))
        self.associatedLabel = QtGui.QLabel(self.layoutWidget1)
        self.associatedLabel.setMinimumSize(QtCore.QSize(0, 25))
        self.associatedLabel.setMaximumSize(QtCore.QSize(16777215, 25))
        self.associatedLabel.setObjectName(_fromUtf8("associatedLabel"))
        self.verticalLayout_2.addWidget(self.associatedLabel)
        self.associatedView = QtGui.QTableView(self.layoutWidget1)
        self.associatedView.setObjectName(_fromUtf8("associatedView"))
        self.verticalLayout_2.addWidget(self.associatedView)
        self.label_8.setBuddy(self.memoTextedit)
        self.label_10.setBuddy(self.multFactorLineedit)
        self.mult_Label.setBuddy(self.multLineedit)
        self.desc_Label.setBuddy(self.descLineedit)
        self.baseno_Label.setBuddy(self.baseCombo)
        self.volume_Label.setBuddy(self.volumeLineedit)
        self.date_Label.setBuddy(self.dateEdit)
        self.associatedLabel.setBuddy(self.associatedView)

        self.retranslateUi(BatchForm)
        QtCore.QMetaObject.connectSlotsByName(BatchForm)
        BatchForm.setTabOrder(self.baseCombo, self.dateEdit)
        BatchForm.setTabOrder(self.dateEdit, self.detailView)
        BatchForm.setTabOrder(self.detailView, self.memoTextedit)
        BatchForm.setTabOrder(self.memoTextedit, self.multLineedit)
        BatchForm.setTabOrder(self.multLineedit, self.descLineedit)
        BatchForm.setTabOrder(self.descLineedit, self.volumeLineedit)
        BatchForm.setTabOrder(self.volumeLineedit, self.multFactorLineedit)
        BatchForm.setTabOrder(self.multFactorLineedit, self.associatedView)
        BatchForm.setTabOrder(self.associatedView, self.baseRadio)
        BatchForm.setTabOrder(self.baseRadio, self.batchRadio)

    def retranslateUi(self, BatchForm):
        BatchForm.setWindowTitle(_translate("BatchForm", "Dialog", None))
        self.label_8.setText(_translate("BatchForm", "Notes", None))
        self.label_9.setText(_translate("BatchForm", "Projected Results", None))
        self.label_10.setText(_translate("BatchForm", "Multiplication Factor", None))
        self.mult_Label.setText(_translate("BatchForm", "Multply Batch", None))
        self.desc_Label.setText(_translate("BatchForm", "Description", None))
        self.weight_Label.setText(_translate("BatchForm", "Weight", None))
        self.baseno_Label.setText(_translate("BatchForm", "Base no.", None))
        self.volume_Label.setText(_translate("BatchForm", "Base Volume", None))
        self.date_Label.setText(_translate("BatchForm", "Date", None))
        self.baseID_Label.setText(_translate("BatchForm", "Base ID", None))
        self.label_26.setText(_translate("BatchForm", " TOTAL 11.4 LITRE:", None))
        self.label_27.setText(_translate("BatchForm", " TOTAL 1 LITRE:", None))
        self.label_28.setText(_translate("BatchForm", " TOTAL 4 LITRE :", None))
        self.label_29.setText(_translate("BatchForm", " TOTAL 2 LITRE:", None))
        self.label_30.setText(_translate("BatchForm", " TOTAL 1.5 LITRE:", None))
        self.label_31.setText(_translate("BatchForm", "TOTAL FLU. LITRE:", None))
        self.saveButton.setText(_translate("BatchForm", "&Save", None))
        self.newButton.setText(_translate("BatchForm", "&New", None))
        self.printButton.setText(_translate("BatchForm", "&Print", None))
        self.deleteButton.setText(_translate("BatchForm", "&Delete", None))
        self.closeButton.setText(_translate("BatchForm", "Close", None))
        self.baseRadio.setText(_translate("BatchForm", "Base", None))
        self.batchRadio.setText(_translate("BatchForm", "Batch", None))
        self.header_label.setText(_translate("BatchForm", "Find Transactions:", None))
        self.label_12.setText(_translate("BatchForm", "Cost", None))
        self.associatedLabel.setText(_translate("BatchForm", "Associated Bases", None))

import images_rc
