# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'itemform.ui'
#
# Created: Sun Jul 07 15:54:55 2013
#      by: PyQt4 UI code generator 4.9.6
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_ItemForm(object):
    def setupUi(self, ItemForm):
        ItemForm.setObjectName(_fromUtf8("ItemForm"))
        ItemForm.resize(589, 542)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(ItemForm.sizePolicy().hasHeightForWidth())
        ItemForm.setSizePolicy(sizePolicy)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(_fromUtf8(":/icons/item")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        ItemForm.setWindowIcon(icon)
        self.gridLayout = QtGui.QGridLayout(ItemForm)
        self.gridLayout.setSizeConstraint(QtGui.QLayout.SetFixedSize)
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.frame_6 = QtGui.QFrame(ItemForm)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame_6.sizePolicy().hasHeightForWidth())
        self.frame_6.setSizePolicy(sizePolicy)
        self.frame_6.setMinimumSize(QtCore.QSize(234, 151))
        self.frame_6.setMaximumSize(QtCore.QSize(234, 151))
        self.frame_6.setFrameShape(QtGui.QFrame.Box)
        self.frame_6.setFrameShadow(QtGui.QFrame.Sunken)
        self.frame_6.setObjectName(_fromUtf8("frame_6"))
        self.layoutWidget = QtGui.QWidget(self.frame_6)
        self.layoutWidget.setGeometry(QtCore.QRect(11, 11, 214, 129))
        self.layoutWidget.setObjectName(_fromUtf8("layoutWidget"))
        self.gridLayout_2 = QtGui.QGridLayout(self.layoutWidget)
        self.gridLayout_2.setMargin(0)
        self.gridLayout_2.setObjectName(_fromUtf8("gridLayout_2"))
        self.supplierNo_label = QtGui.QLabel(self.layoutWidget)
        self.supplierNo_label.setObjectName(_fromUtf8("supplierNo_label"))
        self.gridLayout_2.addWidget(self.supplierNo_label, 0, 0, 1, 1)
        self.supplierno_lineEdit = QtGui.QLineEdit(self.layoutWidget)
        self.supplierno_lineEdit.setMinimumSize(QtCore.QSize(150, 25))
        self.supplierno_lineEdit.setMaximumSize(QtCore.QSize(150, 25))
        self.supplierno_lineEdit.setObjectName(_fromUtf8("supplierno_lineEdit"))
        self.gridLayout_2.addWidget(self.supplierno_lineEdit, 0, 1, 1, 1)
        self.supplier_label = QtGui.QLabel(self.layoutWidget)
        self.supplier_label.setObjectName(_fromUtf8("supplier_label"))
        self.gridLayout_2.addWidget(self.supplier_label, 1, 0, 1, 1)
        self.measure_label = QtGui.QLabel(self.layoutWidget)
        self.measure_label.setObjectName(_fromUtf8("measure_label"))
        self.gridLayout_2.addWidget(self.measure_label, 2, 0, 1, 1)
        self.measure_lineEdit = QtGui.QLineEdit(self.layoutWidget)
        self.measure_lineEdit.setMinimumSize(QtCore.QSize(150, 25))
        self.measure_lineEdit.setMaximumSize(QtCore.QSize(150, 25))
        self.measure_lineEdit.setObjectName(_fromUtf8("measure_lineEdit"))
        self.gridLayout_2.addWidget(self.measure_lineEdit, 2, 1, 1, 1)
        self.sup_combo = QtGui.QComboBox(self.layoutWidget)
        self.sup_combo.setEnabled(True)
        self.sup_combo.setMinimumSize(QtCore.QSize(150, 25))
        self.sup_combo.setMaximumSize(QtCore.QSize(150, 25))
        self.sup_combo.setFrame(True)
        self.sup_combo.setObjectName(_fromUtf8("sup_combo"))
        self.gridLayout_2.addWidget(self.sup_combo, 1, 1, 1, 1)
        self.gridLayout.addWidget(self.frame_6, 1, 1, 1, 1)
        self.assembly_frame = QtGui.QFrame(ItemForm)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.assembly_frame.sizePolicy().hasHeightForWidth())
        self.assembly_frame.setSizePolicy(sizePolicy)
        self.assembly_frame.setMinimumSize(QtCore.QSize(571, 188))
        self.assembly_frame.setMaximumSize(QtCore.QSize(571, 188))
        self.assembly_frame.setFrameShape(QtGui.QFrame.StyledPanel)
        self.assembly_frame.setFrameShadow(QtGui.QFrame.Plain)
        self.assembly_frame.setObjectName(_fromUtf8("assembly_frame"))
        self.label_11 = QtGui.QLabel(self.assembly_frame)
        self.label_11.setGeometry(QtCore.QRect(10, 10, 65, 16))
        self.label_11.setObjectName(_fromUtf8("label_11"))
        self.label_12 = QtGui.QLabel(self.assembly_frame)
        self.label_12.setGeometry(QtCore.QRect(289, 10, 113, 16))
        self.label_12.setObjectName(_fromUtf8("label_12"))
        self.bsView = QtGui.QTableView(self.assembly_frame)
        self.bsView.setGeometry(QtCore.QRect(10, 29, 273, 149))
        self.bsView.setObjectName(_fromUtf8("bsView"))
        self.bmView = QtGui.QTableView(self.assembly_frame)
        self.bmView.setGeometry(QtCore.QRect(289, 29, 272, 149))
        self.bmView.setObjectName(_fromUtf8("bmView"))
        self.gridLayout.addWidget(self.assembly_frame, 4, 0, 1, 3)
        self.frame_7 = QtGui.QFrame(ItemForm)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame_7.sizePolicy().hasHeightForWidth())
        self.frame_7.setSizePolicy(sizePolicy)
        self.frame_7.setMinimumSize(QtCore.QSize(234, 85))
        self.frame_7.setMaximumSize(QtCore.QSize(234, 85))
        self.frame_7.setFrameShape(QtGui.QFrame.Box)
        self.frame_7.setFrameShadow(QtGui.QFrame.Sunken)
        self.frame_7.setObjectName(_fromUtf8("frame_7"))
        self.pack_lineEdit = QtGui.QLineEdit(self.frame_7)
        self.pack_lineEdit.setGeometry(QtCore.QRect(69, 13, 150, 25))
        self.pack_lineEdit.setMinimumSize(QtCore.QSize(150, 25))
        self.pack_lineEdit.setMaximumSize(QtCore.QSize(150, 25))
        self.pack_lineEdit.setInputMask(_fromUtf8(""))
        self.pack_lineEdit.setMaxLength(32767)
        self.pack_lineEdit.setObjectName(_fromUtf8("pack_lineEdit"))
        self.label_7 = QtGui.QLabel(self.frame_7)
        self.label_7.setGeometry(QtCore.QRect(15, 11, 37, 16))
        self.label_7.setObjectName(_fromUtf8("label_7"))
        self.uom_lineEdit = QtGui.QLineEdit(self.frame_7)
        self.uom_lineEdit.setGeometry(QtCore.QRect(69, 47, 150, 25))
        self.uom_lineEdit.setMinimumSize(QtCore.QSize(150, 25))
        self.uom_lineEdit.setMaximumSize(QtCore.QSize(150, 25))
        self.uom_lineEdit.setObjectName(_fromUtf8("uom_lineEdit"))
        self.uom_label = QtGui.QLabel(self.frame_7)
        self.uom_label.setGeometry(QtCore.QRect(15, 46, 44, 16))
        self.uom_label.setObjectName(_fromUtf8("uom_label"))
        self.gridLayout.addWidget(self.frame_7, 2, 1, 1, 1)
        self.frame_5 = QtGui.QFrame(ItemForm)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame_5.sizePolicy().hasHeightForWidth())
        self.frame_5.setSizePolicy(sizePolicy)
        self.frame_5.setMinimumSize(QtCore.QSize(231, 234))
        self.frame_5.setMaximumSize(QtCore.QSize(231, 250))
        self.frame_5.setFrameShape(QtGui.QFrame.Box)
        self.frame_5.setFrameShadow(QtGui.QFrame.Sunken)
        self.frame_5.setObjectName(_fromUtf8("frame_5"))
        self.price_lineEdit = QtGui.QLineEdit(self.frame_5)
        self.price_lineEdit.setGeometry(QtCore.QRect(70, 167, 150, 25))
        self.price_lineEdit.setMinimumSize(QtCore.QSize(150, 25))
        self.price_lineEdit.setMaximumSize(QtCore.QSize(150, 25))
        self.price_lineEdit.setInputMask(_fromUtf8(""))
        self.price_lineEdit.setMaxLength(32767)
        self.price_lineEdit.setObjectName(_fromUtf8("price_lineEdit"))
        self.hachsher_label = QtGui.QLabel(self.frame_5)
        self.hachsher_label.setGeometry(QtCore.QRect(11, 198, 51, 16))
        self.hachsher_label.setObjectName(_fromUtf8("hachsher_label"))
        self.desc_textEdit = QtGui.QTextEdit(self.frame_5)
        self.desc_textEdit.setGeometry(QtCore.QRect(11, 61, 209, 100))
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.desc_textEdit.sizePolicy().hasHeightForWidth())
        self.desc_textEdit.setSizePolicy(sizePolicy)
        self.desc_textEdit.setMaximumSize(QtCore.QSize(240, 100))
        self.desc_textEdit.setTabChangesFocus(True)
        self.desc_textEdit.setObjectName(_fromUtf8("desc_textEdit"))
        self.label = QtGui.QLabel(self.frame_5)
        self.label.setGeometry(QtCore.QRect(11, 11, 42, 16))
        self.label.setObjectName(_fromUtf8("label"))
        self.label_2 = QtGui.QLabel(self.frame_5)
        self.label_2.setGeometry(QtCore.QRect(11, 42, 53, 16))
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.itemno_lineEdit = QtGui.QLineEdit(self.frame_5)
        self.itemno_lineEdit.setGeometry(QtCore.QRect(70, 11, 150, 25))
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.itemno_lineEdit.sizePolicy().hasHeightForWidth())
        self.itemno_lineEdit.setSizePolicy(sizePolicy)
        self.itemno_lineEdit.setMinimumSize(QtCore.QSize(150, 25))
        self.itemno_lineEdit.setMaximumSize(QtCore.QSize(150, 25))
        self.itemno_lineEdit.setBaseSize(QtCore.QSize(0, 0))
        self.itemno_lineEdit.setFrame(True)
        self.itemno_lineEdit.setObjectName(_fromUtf8("itemno_lineEdit"))
        self.label_10 = QtGui.QLabel(self.frame_5)
        self.label_10.setGeometry(QtCore.QRect(11, 167, 23, 16))
        self.label_10.setObjectName(_fromUtf8("label_10"))
        self.hachsher_lineEdit = QtGui.QLineEdit(self.frame_5)
        self.hachsher_lineEdit.setGeometry(QtCore.QRect(70, 198, 150, 25))
        self.hachsher_lineEdit.setMinimumSize(QtCore.QSize(150, 25))
        self.hachsher_lineEdit.setMaximumSize(QtCore.QSize(150, 25))
        self.hachsher_lineEdit.setObjectName(_fromUtf8("hachsher_lineEdit"))
        self.gridLayout.addWidget(self.frame_5, 1, 0, 2, 1)
        self.horizontalLayout_3 = QtGui.QHBoxLayout()
        self.horizontalLayout_3.setObjectName(_fromUtf8("horizontalLayout_3"))
        self.horizontalLayout_2 = QtGui.QHBoxLayout()
        self.horizontalLayout_2.setContentsMargins(0, -1, 41, -1)
        self.horizontalLayout_2.setObjectName(_fromUtf8("horizontalLayout_2"))
        self.label_9 = QtGui.QLabel(ItemForm)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_9.sizePolicy().hasHeightForWidth())
        self.label_9.setSizePolicy(sizePolicy)
        self.label_9.setObjectName(_fromUtf8("label_9"))
        self.horizontalLayout_2.addWidget(self.label_9)
        self.type_comboBox = QtGui.QComboBox(ItemForm)
        self.type_comboBox.setMinimumSize(QtCore.QSize(150, 25))
        self.type_comboBox.setMaximumSize(QtCore.QSize(150, 25))
        self.type_comboBox.setObjectName(_fromUtf8("type_comboBox"))
        self.type_comboBox.addItem(_fromUtf8(""))
        self.type_comboBox.addItem(_fromUtf8(""))
        self.horizontalLayout_2.addWidget(self.type_comboBox)
        self.horizontalLayout_3.addLayout(self.horizontalLayout_2)
        self.horizontalLayout = QtGui.QHBoxLayout()
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        self.itemno_pushButton = QtGui.QPushButton(ItemForm)
        self.itemno_pushButton.setObjectName(_fromUtf8("itemno_pushButton"))
        self.horizontalLayout.addWidget(self.itemno_pushButton)
        self.inactive_checkBox = QtGui.QCheckBox(ItemForm)
        self.inactive_checkBox.setObjectName(_fromUtf8("inactive_checkBox"))
        self.horizontalLayout.addWidget(self.inactive_checkBox)
        self.mixitem_checkBox = QtGui.QCheckBox(ItemForm)
        self.mixitem_checkBox.setObjectName(_fromUtf8("mixitem_checkBox"))
        self.horizontalLayout.addWidget(self.mixitem_checkBox)
        self.horizontalLayout_3.addLayout(self.horizontalLayout)
        self.gridLayout.addLayout(self.horizontalLayout_3, 0, 0, 1, 2)
        self.horizontalLayout_4 = QtGui.QHBoxLayout()
        self.horizontalLayout_4.setObjectName(_fromUtf8("horizontalLayout_4"))
        self.line = QtGui.QFrame(ItemForm)
        self.line.setFrameShape(QtGui.QFrame.VLine)
        self.line.setFrameShadow(QtGui.QFrame.Sunken)
        self.line.setObjectName(_fromUtf8("line"))
        self.horizontalLayout_4.addWidget(self.line)
        self.verticalLayout = QtGui.QVBoxLayout()
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.new_pushButton = QtGui.QPushButton(ItemForm)
        self.new_pushButton.setMinimumSize(QtCore.QSize(0, 30))
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(_fromUtf8(":/icons/new")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.new_pushButton.setIcon(icon1)
        self.new_pushButton.setIconSize(QtCore.QSize(20, 20))
        self.new_pushButton.setObjectName(_fromUtf8("new_pushButton"))
        self.verticalLayout.addWidget(self.new_pushButton)
        self.save_pushButton = QtGui.QPushButton(ItemForm)
        self.save_pushButton.setMinimumSize(QtCore.QSize(0, 30))
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(_fromUtf8(":/icons/save")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.save_pushButton.setIcon(icon2)
        self.save_pushButton.setIconSize(QtCore.QSize(20, 20))
        self.save_pushButton.setObjectName(_fromUtf8("save_pushButton"))
        self.verticalLayout.addWidget(self.save_pushButton)
        self.close_pushButton = QtGui.QPushButton(ItemForm)
        self.close_pushButton.setMinimumSize(QtCore.QSize(0, 30))
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap(_fromUtf8(":/icons/exit")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.close_pushButton.setIcon(icon3)
        self.close_pushButton.setIconSize(QtCore.QSize(20, 20))
        self.close_pushButton.setObjectName(_fromUtf8("close_pushButton"))
        self.verticalLayout.addWidget(self.close_pushButton)
        self.delete_pushButton = QtGui.QPushButton(ItemForm)
        self.delete_pushButton.setMinimumSize(QtCore.QSize(0, 30))
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap(_fromUtf8(":/icons/delete")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.delete_pushButton.setIcon(icon4)
        self.delete_pushButton.setIconSize(QtCore.QSize(20, 20))
        self.delete_pushButton.setObjectName(_fromUtf8("delete_pushButton"))
        self.verticalLayout.addWidget(self.delete_pushButton)
        self.find_pushButton = QtGui.QPushButton(ItemForm)
        self.find_pushButton.setMinimumSize(QtCore.QSize(0, 30))
        icon5 = QtGui.QIcon()
        icon5.addPixmap(QtGui.QPixmap(_fromUtf8(":/icons/find")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.find_pushButton.setIcon(icon5)
        self.find_pushButton.setIconSize(QtCore.QSize(20, 20))
        self.find_pushButton.setObjectName(_fromUtf8("find_pushButton"))
        self.verticalLayout.addWidget(self.find_pushButton)
        spacerItem = QtGui.QSpacerItem(72, 13, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem)
        self.horizontalLayout_4.addLayout(self.verticalLayout)
        self.gridLayout.addLayout(self.horizontalLayout_4, 0, 2, 3, 1)
        self.qbFrame = QtGui.QFrame(ItemForm)
        self.qbFrame.setFrameShape(QtGui.QFrame.Box)
        self.qbFrame.setFrameShadow(QtGui.QFrame.Raised)
        self.qbFrame.setObjectName(_fromUtf8("qbFrame"))
        self.formLayout = QtGui.QFormLayout(self.qbFrame)
        self.formLayout.setObjectName(_fromUtf8("formLayout"))
        self.horizontalLayout_5 = QtGui.QHBoxLayout()
        self.horizontalLayout_5.setObjectName(_fromUtf8("horizontalLayout_5"))
        self.label_3 = QtGui.QLabel(self.qbFrame)
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.horizontalLayout_5.addWidget(self.label_3)
        self.qbParent_lineEdit = QtGui.QLineEdit(self.qbFrame)
        self.qbParent_lineEdit.setMinimumSize(QtCore.QSize(150, 25))
        self.qbParent_lineEdit.setObjectName(_fromUtf8("qbParent_lineEdit"))
        self.horizontalLayout_5.addWidget(self.qbParent_lineEdit)
        self.label_4 = QtGui.QLabel(self.qbFrame)
        self.label_4.setObjectName(_fromUtf8("label_4"))
        self.horizontalLayout_5.addWidget(self.label_4)
        self.qbAccount_lineEdit = QtGui.QLineEdit(self.qbFrame)
        self.qbAccount_lineEdit.setMinimumSize(QtCore.QSize(150, 25))
        self.qbAccount_lineEdit.setObjectName(_fromUtf8("qbAccount_lineEdit"))
        self.horizontalLayout_5.addWidget(self.qbAccount_lineEdit)
        self.formLayout.setLayout(0, QtGui.QFormLayout.SpanningRole, self.horizontalLayout_5)
        self.gridLayout.addWidget(self.qbFrame, 3, 0, 1, 2)
        self.supplierNo_label.setBuddy(self.supplierno_lineEdit)
        self.supplier_label.setBuddy(self.sup_combo)
        self.measure_label.setBuddy(self.measure_lineEdit)
        self.label_11.setBuddy(self.bsView)
        self.label_12.setBuddy(self.bmView)
        self.label_7.setBuddy(self.pack_lineEdit)
        self.uom_label.setBuddy(self.uom_lineEdit)
        self.hachsher_label.setBuddy(self.hachsher_lineEdit)
        self.label.setBuddy(self.itemno_lineEdit)
        self.label_2.setBuddy(self.desc_textEdit)
        self.label_10.setBuddy(self.price_lineEdit)
        self.label_9.setBuddy(self.type_comboBox)

        self.retranslateUi(ItemForm)
        QtCore.QMetaObject.connectSlotsByName(ItemForm)
        ItemForm.setTabOrder(self.type_comboBox, self.itemno_pushButton)
        ItemForm.setTabOrder(self.itemno_pushButton, self.itemno_lineEdit)
        ItemForm.setTabOrder(self.itemno_lineEdit, self.desc_textEdit)
        ItemForm.setTabOrder(self.desc_textEdit, self.price_lineEdit)
        ItemForm.setTabOrder(self.price_lineEdit, self.hachsher_lineEdit)
        ItemForm.setTabOrder(self.hachsher_lineEdit, self.supplierno_lineEdit)
        ItemForm.setTabOrder(self.supplierno_lineEdit, self.sup_combo)
        ItemForm.setTabOrder(self.sup_combo, self.measure_lineEdit)
        ItemForm.setTabOrder(self.measure_lineEdit, self.pack_lineEdit)
        ItemForm.setTabOrder(self.pack_lineEdit, self.uom_lineEdit)
        ItemForm.setTabOrder(self.uom_lineEdit, self.bsView)
        ItemForm.setTabOrder(self.bsView, self.bmView)
        ItemForm.setTabOrder(self.bmView, self.inactive_checkBox)
        ItemForm.setTabOrder(self.inactive_checkBox, self.mixitem_checkBox)
        ItemForm.setTabOrder(self.mixitem_checkBox, self.save_pushButton)
        ItemForm.setTabOrder(self.save_pushButton, self.new_pushButton)
        ItemForm.setTabOrder(self.new_pushButton, self.close_pushButton)
        ItemForm.setTabOrder(self.close_pushButton, self.find_pushButton)
        ItemForm.setTabOrder(self.find_pushButton, self.delete_pushButton)

    def retranslateUi(self, ItemForm):
        ItemForm.setWindowTitle(_translate("ItemForm", "Dialog", None))
        self.supplierNo_label.setText(_translate("ItemForm", "Suppier No.", None))
        self.supplier_label.setText(_translate("ItemForm", "Supplier", None))
        self.measure_label.setText(_translate("ItemForm", "Measure", None))
        self.label_11.setText(_translate("ItemForm", "Base Assemly", None))
        self.label_12.setText(_translate("ItemForm", "Bill of material assembly", None))
        self.label_7.setText(_translate("ItemForm", "Pack Of", None))
        self.uom_label.setText(_translate("ItemForm", "Our UOM", None))
        self.hachsher_label.setText(_translate("ItemForm", "Hachesher", None))
        self.label.setText(_translate("ItemForm", "Item No.", None))
        self.label_2.setText(_translate("ItemForm", "Description", None))
        self.label_10.setText(_translate("ItemForm", "Price", None))
        self.label_9.setText(_translate("ItemForm", "Type", None))
        self.type_comboBox.setItemText(0, _translate("ItemForm", "Raw Material", None))
        self.type_comboBox.setItemText(1, _translate("ItemForm", "Finished Good", None))
        self.itemno_pushButton.setText(_translate("ItemForm", "Item No.", None))
        self.inactive_checkBox.setText(_translate("ItemForm", "Inactive", None))
        self.mixitem_checkBox.setText(_translate("ItemForm", "Mix Item", None))
        self.new_pushButton.setText(_translate("ItemForm", "New", None))
        self.save_pushButton.setText(_translate("ItemForm", "Save", None))
        self.close_pushButton.setText(_translate("ItemForm", "Close", None))
        self.delete_pushButton.setText(_translate("ItemForm", "Delete", None))
        self.find_pushButton.setText(_translate("ItemForm", "Find", None))
        self.label_3.setText(_translate("ItemForm", "QB Parent", None))
        self.label_4.setText(_translate("ItemForm", "QB Account", None))

import images_rc
