# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'settingsform.ui'
#
# Created: Wed Aug 07 18:33:37 2013
#      by: PyQt4 UI code generator 4.9.6
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_SettingsForm(object):
    def setupUi(self, SettingsForm):
        SettingsForm.setObjectName(_fromUtf8("SettingsForm"))
        SettingsForm.resize(400, 344)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(_fromUtf8(":/icons/settings")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        SettingsForm.setWindowIcon(icon)
        self.gridLayout_3 = QtGui.QGridLayout(SettingsForm)
        self.gridLayout_3.setObjectName(_fromUtf8("gridLayout_3"))
        self.close_pushButton = QtGui.QPushButton(SettingsForm)
        self.close_pushButton.setObjectName(_fromUtf8("close_pushButton"))
        self.gridLayout_3.addWidget(self.close_pushButton, 1, 2, 1, 1)
        spacerItem = QtGui.QSpacerItem(217, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridLayout_3.addItem(spacerItem, 1, 0, 1, 1)
        self.settings_tabWidget = QtGui.QTabWidget(SettingsForm)
        self.settings_tabWidget.setObjectName(_fromUtf8("settings_tabWidget"))
        self.tab = QtGui.QWidget()
        self.tab.setObjectName(_fromUtf8("tab"))
        self.verticalLayout_6 = QtGui.QVBoxLayout(self.tab)
        self.verticalLayout_6.setObjectName(_fromUtf8("verticalLayout_6"))
        self.groupBox = QtGui.QGroupBox(self.tab)
        self.groupBox.setObjectName(_fromUtf8("groupBox"))
        self.verticalLayout_2 = QtGui.QVBoxLayout(self.groupBox)
        self.verticalLayout_2.setObjectName(_fromUtf8("verticalLayout_2"))
        self.bomPrice_checkBox = QtGui.QCheckBox(self.groupBox)
        self.bomPrice_checkBox.setObjectName(_fromUtf8("bomPrice_checkBox"))
        self.verticalLayout_2.addWidget(self.bomPrice_checkBox)
        self.priceCheck_checkBox = QtGui.QCheckBox(self.groupBox)
        self.priceCheck_checkBox.setObjectName(_fromUtf8("priceCheck_checkBox"))
        self.verticalLayout_2.addWidget(self.priceCheck_checkBox)
        self.horizontalLayout_3 = QtGui.QHBoxLayout()
        self.horizontalLayout_3.setObjectName(_fromUtf8("horizontalLayout_3"))
        self.verticalLayout = QtGui.QVBoxLayout()
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.label = QtGui.QLabel(self.groupBox)
        self.label.setObjectName(_fromUtf8("label"))
        self.verticalLayout.addWidget(self.label)
        self.horizontalLayout_2 = QtGui.QHBoxLayout()
        self.horizontalLayout_2.setObjectName(_fromUtf8("horizontalLayout_2"))
        self.priceDiff_lineEdit = QtGui.QLineEdit(self.groupBox)
        self.priceDiff_lineEdit.setMinimumSize(QtCore.QSize(0, 25))
        self.priceDiff_lineEdit.setMaximumSize(QtCore.QSize(75, 16777215))
        self.priceDiff_lineEdit.setObjectName(_fromUtf8("priceDiff_lineEdit"))
        self.horizontalLayout_2.addWidget(self.priceDiff_lineEdit)
        spacerItem1 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem1)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.horizontalLayout_3.addLayout(self.verticalLayout)
        spacerItem2 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem2)
        self.verticalLayout_2.addLayout(self.horizontalLayout_3)
        self.verticalLayout_6.addWidget(self.groupBox)
        spacerItem3 = QtGui.QSpacerItem(20, 61, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout_6.addItem(spacerItem3)
        self.defDate_groupBox = QtGui.QGroupBox(self.tab)
        self.defDate_groupBox.setObjectName(_fromUtf8("defDate_groupBox"))
        self.horizontalLayout = QtGui.QHBoxLayout(self.defDate_groupBox)
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        self.currDate_radioButton = QtGui.QRadioButton(self.defDate_groupBox)
        self.currDate_radioButton.setObjectName(_fromUtf8("currDate_radioButton"))
        self.horizontalLayout.addWidget(self.currDate_radioButton)
        self.lastDate_radioButton = QtGui.QRadioButton(self.defDate_groupBox)
        self.lastDate_radioButton.setObjectName(_fromUtf8("lastDate_radioButton"))
        self.horizontalLayout.addWidget(self.lastDate_radioButton)
        self.verticalLayout_6.addWidget(self.defDate_groupBox)
        self.settings_tabWidget.addTab(self.tab, _fromUtf8(""))
        self.tab_2 = QtGui.QWidget()
        self.tab_2.setObjectName(_fromUtf8("tab_2"))
        self.verticalLayout_5 = QtGui.QVBoxLayout(self.tab_2)
        self.verticalLayout_5.setObjectName(_fromUtf8("verticalLayout_5"))
        self.closingDate_groupBox = QtGui.QGroupBox(self.tab_2)
        self.closingDate_groupBox.setObjectName(_fromUtf8("closingDate_groupBox"))
        self.gridLayout = QtGui.QGridLayout(self.closingDate_groupBox)
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.closingDate_lineEdit = QtGui.QLineEdit(self.closingDate_groupBox)
        self.closingDate_lineEdit.setObjectName(_fromUtf8("closingDate_lineEdit"))
        self.gridLayout.addWidget(self.closingDate_lineEdit, 2, 1, 1, 1)
        self.closingDate_dateEdit = QtGui.QDateEdit(self.closingDate_groupBox)
        self.closingDate_dateEdit.setObjectName(_fromUtf8("closingDate_dateEdit"))
        self.gridLayout.addWidget(self.closingDate_dateEdit, 2, 0, 1, 1)
        self.label_3 = QtGui.QLabel(self.closingDate_groupBox)
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.gridLayout.addWidget(self.label_3, 1, 1, 1, 1)
        self.label_2 = QtGui.QLabel(self.closingDate_groupBox)
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.gridLayout.addWidget(self.label_2, 1, 0, 1, 1)
        self.closingDate_checkBox = QtGui.QCheckBox(self.closingDate_groupBox)
        self.closingDate_checkBox.setObjectName(_fromUtf8("closingDate_checkBox"))
        self.gridLayout.addWidget(self.closingDate_checkBox, 0, 0, 1, 1)
        self.verticalLayout_5.addWidget(self.closingDate_groupBox)
        spacerItem4 = QtGui.QSpacerItem(20, 92, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout_5.addItem(spacerItem4)
        self.mergeBom_groupBox = QtGui.QGroupBox(self.tab_2)
        self.mergeBom_groupBox.setObjectName(_fromUtf8("mergeBom_groupBox"))
        self.verticalLayout_7 = QtGui.QVBoxLayout(self.mergeBom_groupBox)
        self.verticalLayout_7.setObjectName(_fromUtf8("verticalLayout_7"))
        self.horizontalLayout_5 = QtGui.QHBoxLayout()
        self.horizontalLayout_5.setObjectName(_fromUtf8("horizontalLayout_5"))
        self.verticalLayout_3 = QtGui.QVBoxLayout()
        self.verticalLayout_3.setObjectName(_fromUtf8("verticalLayout_3"))
        self.label_4 = QtGui.QLabel(self.mergeBom_groupBox)
        self.label_4.setObjectName(_fromUtf8("label_4"))
        self.verticalLayout_3.addWidget(self.label_4)
        self.del_comboBox = QtGui.QComboBox(self.mergeBom_groupBox)
        self.del_comboBox.setObjectName(_fromUtf8("del_comboBox"))
        self.verticalLayout_3.addWidget(self.del_comboBox)
        self.horizontalLayout_5.addLayout(self.verticalLayout_3)
        self.verticalLayout_4 = QtGui.QVBoxLayout()
        self.verticalLayout_4.setObjectName(_fromUtf8("verticalLayout_4"))
        self.label_5 = QtGui.QLabel(self.mergeBom_groupBox)
        self.label_5.setObjectName(_fromUtf8("label_5"))
        self.verticalLayout_4.addWidget(self.label_5)
        self.cont_comboBox = QtGui.QComboBox(self.mergeBom_groupBox)
        self.cont_comboBox.setObjectName(_fromUtf8("cont_comboBox"))
        self.verticalLayout_4.addWidget(self.cont_comboBox)
        self.horizontalLayout_5.addLayout(self.verticalLayout_4)
        self.verticalLayout_7.addLayout(self.horizontalLayout_5)
        self.horizontalLayout_4 = QtGui.QHBoxLayout()
        self.horizontalLayout_4.setObjectName(_fromUtf8("horizontalLayout_4"))
        spacerItem5 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem5)
        self.merge_pushButton = QtGui.QPushButton(self.mergeBom_groupBox)
        self.merge_pushButton.setObjectName(_fromUtf8("merge_pushButton"))
        self.horizontalLayout_4.addWidget(self.merge_pushButton)
        self.verticalLayout_7.addLayout(self.horizontalLayout_4)
        self.verticalLayout_5.addWidget(self.mergeBom_groupBox)
        self.settings_tabWidget.addTab(self.tab_2, _fromUtf8(""))
        self.tab_3 = QtGui.QWidget()
        self.tab_3.setObjectName(_fromUtf8("tab_3"))
        self.gridLayout_5 = QtGui.QGridLayout(self.tab_3)
        self.gridLayout_5.setObjectName(_fromUtf8("gridLayout_5"))
        self.frame = QtGui.QFrame(self.tab_3)
        self.frame.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtGui.QFrame.Raised)
        self.frame.setObjectName(_fromUtf8("frame"))
        self.gridLayout_2 = QtGui.QGridLayout(self.frame)
        self.gridLayout_2.setObjectName(_fromUtf8("gridLayout_2"))
        self.label_6 = QtGui.QLabel(self.frame)
        self.label_6.setObjectName(_fromUtf8("label_6"))
        self.gridLayout_2.addWidget(self.label_6, 0, 0, 1, 1)
        self.ap_lineEdit = QtGui.QLineEdit(self.frame)
        self.ap_lineEdit.setMinimumSize(QtCore.QSize(0, 25))
        self.ap_lineEdit.setObjectName(_fromUtf8("ap_lineEdit"))
        self.gridLayout_2.addWidget(self.ap_lineEdit, 0, 1, 1, 1)
        self.label_7 = QtGui.QLabel(self.frame)
        self.label_7.setObjectName(_fromUtf8("label_7"))
        self.gridLayout_2.addWidget(self.label_7, 1, 0, 1, 1)
        self.apUSD_lineEdit = QtGui.QLineEdit(self.frame)
        self.apUSD_lineEdit.setMinimumSize(QtCore.QSize(0, 25))
        self.apUSD_lineEdit.setObjectName(_fromUtf8("apUSD_lineEdit"))
        self.gridLayout_2.addWidget(self.apUSD_lineEdit, 1, 1, 1, 1)
        self.label_8 = QtGui.QLabel(self.frame)
        self.label_8.setObjectName(_fromUtf8("label_8"))
        self.gridLayout_2.addWidget(self.label_8, 2, 0, 1, 1)
        self.inv_lineEdit = QtGui.QLineEdit(self.frame)
        self.inv_lineEdit.setMinimumSize(QtCore.QSize(0, 25))
        self.inv_lineEdit.setObjectName(_fromUtf8("inv_lineEdit"))
        self.gridLayout_2.addWidget(self.inv_lineEdit, 2, 1, 1, 1)
        self.label_9 = QtGui.QLabel(self.frame)
        self.label_9.setObjectName(_fromUtf8("label_9"))
        self.gridLayout_2.addWidget(self.label_9, 3, 0, 1, 1)
        self.class_lineEdit = QtGui.QLineEdit(self.frame)
        self.class_lineEdit.setMinimumSize(QtCore.QSize(0, 25))
        self.class_lineEdit.setObjectName(_fromUtf8("class_lineEdit"))
        self.gridLayout_2.addWidget(self.class_lineEdit, 3, 1, 1, 1)
        self.gridLayout_5.addWidget(self.frame, 0, 0, 1, 1)
        self.settings_tabWidget.addTab(self.tab_3, _fromUtf8(""))
        self.tab_4 = QtGui.QWidget()
        self.tab_4.setObjectName(_fromUtf8("tab_4"))
        self.gridLayout_6 = QtGui.QGridLayout(self.tab_4)
        self.gridLayout_6.setObjectName(_fromUtf8("gridLayout_6"))
        self.label_10 = QtGui.QLabel(self.tab_4)
        self.label_10.setObjectName(_fromUtf8("label_10"))
        self.gridLayout_6.addWidget(self.label_10, 0, 0, 1, 1)
        self.list_comboBox = QtGui.QComboBox(self.tab_4)
        self.list_comboBox.setObjectName(_fromUtf8("list_comboBox"))
        self.gridLayout_6.addWidget(self.list_comboBox, 0, 1, 1, 1)
        self.list_tableView = QtGui.QTableView(self.tab_4)
        self.list_tableView.setObjectName(_fromUtf8("list_tableView"))
        self.gridLayout_6.addWidget(self.list_tableView, 1, 0, 1, 2)
        self.settings_tabWidget.addTab(self.tab_4, _fromUtf8(""))
        self.tab_5 = QtGui.QWidget()
        self.tab_5.setObjectName(_fromUtf8("tab_5"))
        self.verticalLayout_8 = QtGui.QVBoxLayout(self.tab_5)
        self.verticalLayout_8.setObjectName(_fromUtf8("verticalLayout_8"))
        self.horizontalLayout_6 = QtGui.QHBoxLayout()
        self.horizontalLayout_6.setObjectName(_fromUtf8("horizontalLayout_6"))
        self.label_11 = QtGui.QLabel(self.tab_5)
        self.label_11.setObjectName(_fromUtf8("label_11"))
        self.horizontalLayout_6.addWidget(self.label_11)
        self.logFilter_lineEdit = QtGui.QLineEdit(self.tab_5)
        self.logFilter_lineEdit.setMinimumSize(QtCore.QSize(0, 25))
        self.logFilter_lineEdit.setObjectName(_fromUtf8("logFilter_lineEdit"))
        self.horizontalLayout_6.addWidget(self.logFilter_lineEdit)
        self.label_12 = QtGui.QLabel(self.tab_5)
        self.label_12.setObjectName(_fromUtf8("label_12"))
        self.horizontalLayout_6.addWidget(self.label_12)
        self.logField_comboBox = QtGui.QComboBox(self.tab_5)
        self.logField_comboBox.setMinimumSize(QtCore.QSize(100, 25))
        self.logField_comboBox.setObjectName(_fromUtf8("logField_comboBox"))
        self.horizontalLayout_6.addWidget(self.logField_comboBox)
        self.verticalLayout_8.addLayout(self.horizontalLayout_6)
        self.log_tableView = QtGui.QTableView(self.tab_5)
        self.log_tableView.setObjectName(_fromUtf8("log_tableView"))
        self.verticalLayout_8.addWidget(self.log_tableView)
        self.settings_tabWidget.addTab(self.tab_5, _fromUtf8(""))
        self.gridLayout_3.addWidget(self.settings_tabWidget, 0, 0, 1, 4)
        self.save_pushButton = QtGui.QPushButton(SettingsForm)
        self.save_pushButton.setObjectName(_fromUtf8("save_pushButton"))
        self.gridLayout_3.addWidget(self.save_pushButton, 1, 1, 1, 1)
        self.label_3.setBuddy(self.closingDate_lineEdit)
        self.label_2.setBuddy(self.closingDate_dateEdit)
        self.label_4.setBuddy(self.del_comboBox)
        self.label_5.setBuddy(self.cont_comboBox)

        self.retranslateUi(SettingsForm)
        self.settings_tabWidget.setCurrentIndex(4)
        QtCore.QMetaObject.connectSlotsByName(SettingsForm)

    def retranslateUi(self, SettingsForm):
        SettingsForm.setWindowTitle(_translate("SettingsForm", "Settings", None))
        self.close_pushButton.setText(_translate("SettingsForm", "Close", None))
        self.groupBox.setTitle(_translate("SettingsForm", "Receive BOM Price", None))
        self.bomPrice_checkBox.setText(_translate("SettingsForm", "Update BOM price when changed while receiving inventory", None))
        self.priceCheck_checkBox.setText(_translate("SettingsForm", "Check for change in price when receiving inventory", None))
        self.label.setText(_translate("SettingsForm", "Specify difference to alert", None))
        self.defDate_groupBox.setTitle(_translate("SettingsForm", "Default Date", None))
        self.currDate_radioButton.setText(_translate("SettingsForm", "Current Date", None))
        self.lastDate_radioButton.setText(_translate("SettingsForm", "Last Used Date", None))
        self.settings_tabWidget.setTabText(self.settings_tabWidget.indexOf(self.tab), _translate("SettingsForm", "General", None))
        self.closingDate_groupBox.setTitle(_translate("SettingsForm", "Closing Date", None))
        self.label_3.setText(_translate("SettingsForm", "Password", None))
        self.label_2.setText(_translate("SettingsForm", "Select Date", None))
        self.closingDate_checkBox.setText(_translate("SettingsForm", "Use Closing Date", None))
        self.mergeBom_groupBox.setTitle(_translate("SettingsForm", "Merge BOM", None))
        self.label_4.setText(_translate("SettingsForm", "BOM to be Deleted", None))
        self.label_5.setText(_translate("SettingsForm", "BOM to be Continued", None))
        self.merge_pushButton.setText(_translate("SettingsForm", "Merge", None))
        self.settings_tabWidget.setTabText(self.settings_tabWidget.indexOf(self.tab_2), _translate("SettingsForm", "Tools", None))
        self.label_6.setText(_translate("SettingsForm", "AP Account", None))
        self.label_7.setText(_translate("SettingsForm", "AP USD Account", None))
        self.label_8.setText(_translate("SettingsForm", "Inventory Account", None))
        self.label_9.setText(_translate("SettingsForm", "Class", None))
        self.settings_tabWidget.setTabText(self.settings_tabWidget.indexOf(self.tab_3), _translate("SettingsForm", "Export", None))
        self.label_10.setText(_translate("SettingsForm", "Select list to edit", None))
        self.settings_tabWidget.setTabText(self.settings_tabWidget.indexOf(self.tab_4), _translate("SettingsForm", "Lists", None))
        self.label_11.setText(_translate("SettingsForm", "Filter By", None))
        self.label_12.setText(_translate("SettingsForm", "In Field", None))
        self.settings_tabWidget.setTabText(self.settings_tabWidget.indexOf(self.tab_5), _translate("SettingsForm", "Audit Log", None))
        self.save_pushButton.setText(_translate("SettingsForm", "Save", None))

import images_rc
